"""
Seed Credit Cards Database
Real Indian Credit Cards
"""

from sqlalchemy.orm import Session
from database.models import Card, ChurnRisk
from database.session import SessionLocal
import logging

logger = logging.getLogger(__name__)


def seed_cards(db: Session):
    """Seed the database with real Indian credit card data"""
    
    # Check if cards already exist
    existing_count = db.query(Card).count()
    if existing_count > 0:
        logger.info(f"Cards already seeded ({existing_count} cards). Skipping.")
        return
    
    cards_data = [
        # HDFC Bank
        {
            "name": "HDFC Infinia Metal",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 12500,
            "annual_fee": 12500,
            "reward_rate": 3.3,
            "reward_caps": {"all": None},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"reward_multiplier": 2, "partners": ["Zomato", "Swiggy"]},
            "travel_benefits": {"lounge_access": "unlimited", "insurance": True},
            "shopping_benefits": {"reward_multiplier": 2},
            "other_benefits": {"concierge": True, "golf": "12 rounds/year"},
            "min_income": 2500000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {"150000": 10000, "800000": 15000},
            "annual_waiver_condition": "Spend ₹8L in a year",
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "dining", "lifestyle"],
            "highlight": "Unlimited airport lounge access + 5 reward points per ₹150 on all spends",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "HDFC Diners Club Black",
            "issuer": "HDFC Bank",
            "network": "Diners",
            "joining_fee": 10000,
            "annual_fee": 10000,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True},
            "min_income": 2000000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "dining", "lifestyle"],
            "highlight": "10X rewards on select partners + unlimited global lounge access",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "HDFC Millennia",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 1000,
            "annual_fee": 1000,
            "reward_rate": 5.0,
            "reward_caps": {"cashback_monthly": 1000},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"cashback": 5},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Amazon", "Flipkart"]},
            "other_benefits": {},
            "min_income": 350000,
            "min_cibil": 700,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1L in a year",
            "redemption_ratio": 0.3,
            "tags": ["cashback", "shopping", "dining"],
            "highlight": "5% cashback on Amazon, Flipkart, Swiggy, Zomato and more",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC Regalia Gold",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 2500,
            "annual_fee": 2500,
            "reward_rate": 2.6,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 2},
            "travel_benefits": {"lounge_access": "12/year"},
            "shopping_benefits": {"reward_multiplier": 2},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹3L in a year",
            "redemption_ratio": 0.5,
            "tags": ["travel", "shopping", "lifestyle", "dining"],
            "highlight": "4 reward points per ₹150 + complimentary airport lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC MoneyBack+",
            "issuer": "HDFC Bank",
            "network": "Mastercard",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 2.0,
            "reward_caps": {"cashback_monthly": 500},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 2},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹50K in a year",
            "redemption_ratio": 0.25,
            "tags": ["cashback", "shopping"],
            "highlight": "2X cashback on online spends; redemption as cashback or reward points",
            "churn_risk": ChurnRisk.LOW
        },
        
        # SBI Card
        {
            "name": "SBI Card ELITE",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 4999,
            "annual_fee": 4999,
            "reward_rate": 2.5,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "8/year"},
            "shopping_benefits": {"reward_multiplier": 5},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {"300000": 5000},
            "annual_waiver_condition": "Spend ₹5L in a year",
            "redemption_ratio": 0.25,
            "tags": ["travel", "dining", "premium", "lifestyle"],
            "highlight": "5X reward points on dining, groceries, departmental stores; lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "SBI SimplyCLICK",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 1.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10, "partners": ["Amazon", "Cleartrip"]},
            "other_benefits": {},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1L in a year",
            "redemption_ratio": 0.25,
            "tags": ["shopping", "cashback"],
            "highlight": "10X reward points on online shopping with Amazon, Cleartrip, Lenskart etc.",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "SBI Cashback Card",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 999,
            "annual_fee": 999,
            "reward_rate": 5.0,
            "reward_caps": {"monthly_online": 5000},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "5% flat cashback on online spends; 1% on all other spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # ICICI Bank
        {
            "name": "ICICI Bank Sapphiro",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 3500,
            "annual_fee": 3500,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 2},
            "travel_benefits": {"lounge_access": "12/year", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "4 rounds/year"},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹5L in a year",
            "redemption_ratio": 0.25,
            "tags": ["travel", "dining", "premium", "lifestyle"],
            "highlight": "2 PAYBACK points per ₹100; airport lounge + concierge + golf",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "ICICI Amazon Pay",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Amazon"]},
            "other_benefits": {},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "Lifetime free; 5% cashback on Amazon for Prime members",
            "churn_risk": ChurnRisk.HIGH
        },
        
        # Axis Bank
        {
            "name": "Axis Bank Magnus",
            "issuer": "Axis Bank",
            "network": "Mastercard",
            "joining_fee": 10000,
            "annual_fee": 10000,
            "reward_rate": 12.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "unlimited", "transfer_partners": ["Vistara", "Accor"]},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True},
            "min_income": 1800000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {"100000": 25000},
            "annual_waiver_condition": "Spend ₹15L in a year",
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "lifestyle", "dining"],
            "highlight": "35 Edge Reward points per ₹200; unlimited airport lounge access globally",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Axis ACE",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 5.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {"cashback": 4},
            "dining_benefits": {"cashback": 4, "partners": ["Swiggy", "Zomato"]},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Google Pay"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "fuel", "dining"],
            "highlight": "5% cashback on Google Pay; 4% on Swiggy, Zomato, Ola; 2% on others",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Axis Flipkart",
            "issuer": "Axis Bank",
            "network": "Mastercard",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 1.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 1.5, "partners": ["Flipkart"]},
            "other_benefits": {},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["shopping", "cashback"],
            "highlight": "Unlimited 1.5% cashback on Flipkart + 1% elsewhere",
            "churn_risk": ChurnRisk.HIGH
        },
        
        # IDFC FIRST Bank
        {
            "name": "IDFC FIRST Wealth",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["travel", "premium", "lifestyle"],
            "highlight": "Lifetime free premium card; 10X reward points + unlimited lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "IDFC FIRST Millennia",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 1.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10},
            "other_benefits": {"ott_subscription": "Amazon Prime"},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback", "shopping", "dining"],
            "highlight": "Lifetime free; 10X rewards on online shopping; OTT benefits",
            "churn_risk": ChurnRisk.LOW
        },
        
        # American Express
        {
            "name": "Amex Platinum Charge Card",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 60000,
            "annual_fee": 60000,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "centurion", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": "premium", "hotel_status": True},
            "min_income": 5000000,
            "min_cibil": 800,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["premium", "travel", "lifestyle", "dining"],
            "highlight": "Centurion lounge access worldwide + unlimited lounge + 5X points on travel",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Amex Gold Card",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 4500,
            "annual_fee": 4500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 4},
            "travel_benefits": {"transfer_partners": ["British Airways", "Singapore Airlines"]},
            "shopping_benefits": {"reward_multiplier": 4},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 730,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["dining", "travel", "lifestyle"],
            "highlight": "4X points on dining worldwide; 4X on supermarkets; transfer to airlines",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Amex SmartEarn",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 495,
            "annual_fee": 495,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10, "partners": ["Amazon", "Flipkart", "Uber"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1.5L in a year",
            "redemption_ratio": 0.5,
            "tags": ["cashback", "shopping"],
            "highlight": "10X rewards on Amazon, Flipkart, Uber; 5X on other online spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # Standard Chartered
        {
            "name": "Standard Chartered Ultimate",
            "issuer": "Standard Chartered",
            "network": "Mastercard",
            "joining_fee": 5000,
            "annual_fee": 5000,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"cashback": 3.3},
            "dining_benefits": {"cashback": 3.3},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {"cashback": 3.3},
            "other_benefits": {"concierge": True},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹4L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "travel", "premium"],
            "highlight": "3.3% cashback on all spends; unlimited lounge access + concierge",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Standard Chartered Smart",
            "issuer": "Standard Chartered",
            "network": "Mastercard",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 3.0,
            "reward_caps": {"monthly": 2000},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 3},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback"],
            "highlight": "3% flat cashback on online spends; 1.5% on offline spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # Kotak Mahindra Bank
        {
            "name": "Kotak White Reserve",
            "issuer": "Kotak Mahindra Bank",
            "network": "Visa",
            "joining_fee": 12500,
            "annual_fee": 12500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 4},
            "travel_benefits": {"lounge_access": "unlimited", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "unlimited"},
            "min_income": 3000000,
            "min_cibil": 780,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["premium", "travel", "lifestyle"],
            "highlight": "Top-tier premium card; unlimited lounge + concierge + golf",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Kotak 811 Dream Different",
            "issuer": "Kotak Mahindra Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 0.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 0,
            "min_cibil": 0,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback"],
            "highlight": "Lifetime free; cashback on weekly spending milestones",
            "churn_risk": ChurnRisk.LOW
        },
        
        # AU Small Finance Bank
        {
            "name": "AU Bank Zenith+",
            "issuer": "AU Small Finance Bank",
            "network": "Visa",
            "joining_fee": 4999,
            "annual_fee": 4999,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "12 rounds/year"},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹8L in a year",
            "redemption_ratio": 0.25,
            "tags": ["premium", "travel", "lifestyle", "dining"],
            "highlight": "10 reward points per ₹100; unlimited lounge + golf + concierge",
            "churn_risk": ChurnRisk.LOW
        },

        # --- Additional cards (sourced from Paisabazaar / CardCheck listings) ---

        # Axis Bank
        {
            "name": "Axis Atlas",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 5000,
            "annual_fee": 5000,
            "reward_rate": 3.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "18 domestic + 12 intl/year", "miles_program": "EDGE Miles", "transfer_partners": ["multiple airlines", "hotel programs"]},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {"200000": 2500},
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "lifestyle"],
            "highlight": "Airline-agnostic EDGE Miles; up to 5 miles per ₹100 on travel spends",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Axis Bank SELECT",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 3000,
            "annual_fee": 3000,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "6-12/year"},
            "shopping_benefits": {"reward_multiplier": 10, "partners": ["Swiggy", "BigBasket", "District"]},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.2,
            "tags": ["shopping", "travel", "lifestyle"],
            "highlight": "10X rewards on Swiggy, BigBasket & District; complimentary lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Indian Oil Axis Bank",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {"cashback": 4, "surcharge_waiver": "100%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 1},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["fuel", "cashback"],
            "highlight": "4% value back on IndianOil fuel purchases + 100% surcharge waiver",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Airtel Axis Bank",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 10.0,
            "reward_caps": {"monthly": 500},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 10, "partners": ["Swiggy", "Zomato", "Blinkit"]},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {"telecom_cashback": "25% on Airtel bills"},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "dining"],
            "highlight": "25% cashback on Airtel bills via Airtel Thanks app; 10% on Swiggy/Zomato/Blinkit",
            "churn_risk": ChurnRisk.HIGH
        },
        {
            "name": "Axis Bank My Zone",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 500,
            "reward_rate": 1.25,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"partners": ["Swiggy"]},
            "travel_benefits": {"lounge_access": "limited"},
            "shopping_benefits": {},
            "other_benefits": {"ott_subscription": "SonyLIV Premium"},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["dining", "cashback"],
            "highlight": "BOGO movie tickets on District app; free SonyLIV Premium; Swiggy discounts",
            "churn_risk": ChurnRisk.HIGH
        },
        {
            "name": "Axis Bank Vistara",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 1000,
            "annual_fee": 1500,
            "reward_rate": 3.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"transfer_partners": ["Vistara"], "welcome_benefit": "1 complimentary economy ticket"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel"],
            "highlight": "Complimentary Vistara/Air India ticket on joining; 6 CV Points per ₹200 on Vistara",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Axis Cashback",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 1000,
            "annual_fee": 1000,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "Automatic cashback credited to statement; strong online spend rate",
            "churn_risk": ChurnRisk.LOW
        },

        # HDFC Bank
        {
            "name": "Tata Neu Infinity HDFC Bank",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 1499,
            "annual_fee": 1499,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "8 domestic + 4 intl/year"},
            "shopping_benefits": {"cashback": 5, "partners": ["Tata Neu", "Air India", "Westside", "Croma", "BigBasket"]},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["shopping", "cashback", "travel"],
            "highlight": "5% NeuCoins on Tata Neu & partner brands; complimentary lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Tata Neu Plus HDFC Bank",
            "issuer": "HDFC Bank",
            "network": "RuPay",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Tata Neu", "Croma", "BigBasket", "Tata 1mg"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["shopping", "cashback"],
            "highlight": "Up to 7% NeuCoins on Tata Neu spends via app",
            "churn_risk": ChurnRisk.HIGH
        },
        {
            "name": "HDFC Swiggy",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 10.0,
            "reward_caps": {"monthly": 1500},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 10, "partners": ["Swiggy", "Instamart", "Dineout", "Genie"]},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["dining", "cashback", "shopping"],
            "highlight": "10% cashback across Swiggy Food, Instamart, Dineout & Genie",
            "churn_risk": ChurnRisk.HIGH
        },
        {
            "name": "HDFC Diners Club Privilege",
            "issuer": "HDFC Bank",
            "network": "Diners",
            "joining_fee": 1000,
            "annual_fee": 1000,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10, "partners": ["Swiggy", "Zomato", "BookMyShow"]},
            "travel_benefits": {"lounge_access": "yes"},
            "shopping_benefits": {},
            "other_benefits": {"ott_subscription": "Swiggy One + Times Prime"},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["dining", "travel", "lifestyle"],
            "highlight": "Best-value Diners card: 10X on dining/entertainment brands, lounge access at ₹1,000 fee",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC Pixel Play",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 5.0,
            "reward_caps": {"monthly": 500},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "customizable_packs": ["Dining", "Travel", "Grocery", "Fashion", "Electronics"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "Choose your own 5% cashback merchant packs each month, digital-first management",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC Bank Business Regalia",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 2500,
            "annual_fee": 2500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "8/year"},
            "shopping_benefits": {},
            "other_benefits": {"business_cashback": "5% on utilities, telecom, tax payments"},
            "min_income": 1200000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["premium", "travel", "lifestyle"],
            "highlight": "Built for business owners - rewards plus cashback on utilities and tax payments",
            "churn_risk": ChurnRisk.LOW
        },

        # SBI Card
        {
            "name": "PhonePe SBI Card SELECT BLACK",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 1499,
            "annual_fee": 1499,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "yes"},
            "shopping_benefits": {"cashback": 10, "partners": ["PhonePe"]},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "10% reward points on PhonePe spends, 5% on other online spends",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "BPCL SBI Card OCTANE",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 1499,
            "annual_fee": 1499,
            "reward_rate": 7.25,
            "reward_caps": {"monthly": 2500},
            "fuel_benefits": {"cashback": 6.25, "surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "yes"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["fuel", "dining"],
            "highlight": "Up to 7.25% value back on BPCL fuel spends including surcharge waiver",
            "churn_risk": ChurnRisk.LOW
        },

        # ICICI Bank
        {
            "name": "ICICI Bank Rubyx",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 3000,
            "annual_fee": 3000,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "yes"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["travel", "fuel"],
            "highlight": "Balanced rewards card with fuel surcharge waiver and lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "MakeMyTrip ICICI Bank",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 999,
            "annual_fee": 999,
            "reward_rate": 6.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "limited", "partners": ["MakeMyTrip"]},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "cashback"],
            "highlight": "Up to 6% myCash on MakeMyTrip bookings; myCash never expires",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "ICICI Bank Emeralde",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 12000,
            "annual_fee": 12000,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "unlimited", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "unlimited", "spa": True},
            "min_income": 3000000,
            "min_cibil": 780,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["premium", "travel", "lifestyle"],
            "highlight": "Super-premium: unlimited lounge, golf, spa & concierge via Priority Pass",
            "churn_risk": ChurnRisk.MEDIUM
        },

        # IDFC FIRST Bank
        {
            "name": "IDFC FIRST WOW!",
            "issuer": "IDFC FIRST Bank",
            "network": "RuPay",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 1.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"forex_markup": "0%"},
            "shopping_benefits": {"reward_multiplier": 4},
            "other_benefits": {"fd_backed": True},
            "min_income": 0,
            "min_cibil": 0,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback"],
            "highlight": "FD-secured lifetime-free card - zero forex markup, no income proof needed",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "IDFC FIRST Bank Mayura",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 5999,
            "annual_fee": 5999,
            "reward_rate": 2.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"forex_markup": "0%", "lounge_access": "4/quarter"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium"],
            "highlight": "Zero forex markup, 10X rewards on flight/hotel bookings via IDFC app",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "IDFC First Power",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 199,
            "annual_fee": 199,
            "reward_rate": 6.5,
            "reward_caps": {},
            "fuel_benefits": {"cashback": 6.5},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "limited"},
            "shopping_benefits": {"reward_multiplier": 5},
            "other_benefits": {},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["fuel", "shopping"],
            "highlight": "Up to 6.5% fuel savings; 5% on grocery and utility spends",
            "churn_risk": ChurnRisk.LOW
        },

        # American Express
        {
            "name": "American Express Platinum Reserve",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 10000,
            "annual_fee": 10000,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "select domestic", "hotel_benefits": True},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["premium", "travel"],
            "highlight": "1 MR point per ₹50; dedicated Priority Pass and hotel benefits",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "American Express Membership Rewards",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 1000,
            "annual_fee": 4500,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": False,
            "milestones": {"20000": 1000},
            "redemption_ratio": 1.0,
            "tags": ["rewards"],
            "highlight": "Consistent 1 MR point per ₹50 with monthly bonus-spend incentives",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "American Express Platinum Travel",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 5000,
            "annual_fee": 5000,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "select", "partners": ["Taj Hotels"]},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {"190000": 10000, "400000": 25000},
            "redemption_ratio": 1.0,
            "tags": ["travel", "lifestyle"],
            "highlight": "Milestone-based Taj Hotel vouchers plus MR points on annual spend tiers",
            "churn_risk": ChurnRisk.LOW
        },

        # Standard Chartered
        {
            "name": "Standard Chartered DigiSmart",
            "issuer": "Standard Chartered",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 2.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 10, "partners": ["Zomato"]},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 10, "partners": ["Blinkit", "Myntra"]},
            "other_benefits": {"ott_subscription": "Hotstar discount"},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping", "dining"],
            "highlight": "Lifetime free digital-lifestyle card: discounts on Blinkit, Zomato, Myntra, Hotstar",
            "churn_risk": ChurnRisk.HIGH
        },

        # Kotak Mahindra Bank
        {
            "name": "Kotak Cashback+",
            "issuer": "Kotak Mahindra Bank",
            "network": "Visa",
            "joining_fee": 750,
            "annual_fee": 750,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 5},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {"ott_cashback": 5},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "dining", "shopping"],
            "highlight": "5% cashback on online groceries, food delivery, movies and OTT subscriptions",
            "churn_risk": ChurnRisk.LOW
        },

        # AU Small Finance Bank
        {
            "name": "AU LIT",
            "issuer": "AU Small Finance Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "with paid packs"},
            "shopping_benefits": {"customizable_packs": True},
            "other_benefits": {"ott_packs": True},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["cashback", "lifestyle"],
            "highlight": "Lifetime free; activate paid monthly feature packs for up to 5% cashback",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "AU ixigo",
            "issuer": "AU Small Finance Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 2.5,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"forex_markup": "0%", "lounge_access": "2/quarter", "partners": ["ixigo"]},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "cashback"],
            "highlight": "Lifetime free travel card - zero forex, 10% off ixigo bookings",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "AU Altura Plus",
            "issuer": "AU Small Finance Bank",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "4/year"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": True,
            "milestones": {"10000": 100, "20000": 200, "40000": 400},
            "redemption_ratio": 0.25,
            "tags": ["rewards", "dining"],
            "highlight": "Entry-level AU card with milestone cashback on monthly spend tiers",
            "churn_risk": ChurnRisk.LOW
        },

        # HSBC Bank
        {
            "name": "HSBC TravelOne",
            "issuer": "HSBC Bank",
            "network": "Visa",
            "joining_fee": 4999,
            "annual_fee": 4999,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "6 domestic + 4 intl/year", "golf": "4 rounds/year"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {"100000": 3000, "1200000": 10000},
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium"],
            "highlight": "Airline-agnostic travel card; up to 15% off on EaseMyTrip, Yatra, Cleartrip",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HSBC Cashback",
            "issuer": "HSBC Bank",
            "network": "Visa",
            "joining_fee": 999,
            "annual_fee": 999,
            "reward_rate": 10.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 10},
            "travel_benefits": {"lounge_access": "yes"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 600000,
            "min_cibil": 700,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "dining"],
            "highlight": "10% cashback on dining, food delivery and grocery spends",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "HSBC Premier",
            "issuer": "HSBC Bank",
            "network": "Visa",
            "joining_fee": 12000,
            "annual_fee": 20000,
            "reward_rate": 3.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "unlimited", "forex_markup": "0.99%"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 3000000,
            "min_cibil": 780,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["premium", "travel"],
            "highlight": "For HSBC Premier banking customers - unlimited lounge, lowest forex markup",
            "churn_risk": ChurnRisk.MEDIUM
        },

        # Federal Bank
        {
            "name": "Federal Bank Scapia",
            "issuer": "Federal Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "unlimited domestic", "forex_markup": "0%"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "cashback"],
            "highlight": "Lifetime-free travel card - unlimited domestic lounge, zero forex markup",
            "churn_risk": ChurnRisk.LOW
        },

        # Yes Bank
        {
            "name": "YES BANK PaisaSave",
            "issuer": "Yes Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 499,
            "reward_rate": 3.0,
            "reward_caps": {"monthly": 3000},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"cashback": 6},
            "travel_benefits": {"cashback": 6},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1.2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "dining", "travel"],
            "highlight": "6% cashback on dining and travel spends with no merchant restrictions",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Kiwi RuPay",
            "issuer": "Yes Bank",
            "network": "RuPay",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 1.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 1.5},
            "other_benefits": {"upi_linked": True},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback"],
            "highlight": "UPI-linked RuPay card - 1.5% cashback on UPI scan & pay",
            "churn_risk": ChurnRisk.HIGH
        },

        # RBL Bank
        {
            "name": "IndianOil RBL Bank XTRA",
            "issuer": "RBL Bank",
            "network": "Visa",
            "joining_fee": 1500,
            "annual_fee": 1500,
            "reward_rate": 8.5,
            "reward_caps": {},
            "fuel_benefits": {"cashback": 8.5, "surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {"75000": 1000},
            "redemption_ratio": 0.5,
            "tags": ["fuel"],
            "highlight": "Highest-tier IndianOil co-brand: up to 8.5% fuel savings",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "RBL Popcorn",
            "issuer": "RBL Bank",
            "network": "Visa",
            "joining_fee": 1000,
            "annual_fee": 1000,
            "reward_rate": 10.0,
            "reward_caps": {"monthly": 500},
            "fuel_benefits": {},
            "dining_benefits": {"cashback": 5},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {"ott_cashback": 10, "movie_tickets": "2/month"},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "dining"],
            "highlight": "10% cashback on OTT subscriptions; 2 complimentary BookMyShow tickets/month",
            "churn_risk": ChurnRisk.HIGH
        },

        # IndusInd Bank
        {
            "name": "IndusInd Bank Tiger",
            "issuer": "IndusInd Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {"lounge_access": "limited", "forex_markup": "low"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": True,
            "milestones": {"100000": 1000, "250000": 3000},
            "redemption_ratio": 0.5,
            "tags": ["lifestyle", "cashback"],
            "highlight": "Lifetime free with accelerating rewards on annual spend milestones",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "IndusInd Bank Samman RuPay",
            "issuer": "IndusInd Bank",
            "network": "RuPay",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 1.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {"upi_linked": True},
            "min_income": 150000,
            "min_cibil": 630,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback"],
            "highlight": "UPI-linked lifetime-free RuPay card with fuel surcharge waiver",
            "churn_risk": ChurnRisk.LOW
        },

        # BOBCARD
        {
            "name": "BOBCARD Cashback",
            "issuer": "BOBCARD",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "5% cashback on domestic online spends, automatic monthly credit",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "BOBCARD Eterna",
            "issuer": "BOBCARD",
            "network": "Visa",
            "joining_fee": 2499,
            "annual_fee": 2499,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited domestic + 4 intl/year"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["travel", "premium", "dining"],
            "highlight": "Bank of Baroda's flagship - unlimited domestic lounge, 10X on intl & dining",
            "churn_risk": ChurnRisk.LOW
        },
    ]
    
    # Add all cards
    for card_data in cards_data:
        card = Card(**card_data)
        db.add(card)
    
    db.commit()
    logger.info(f"Seeded {len(cards_data)} credit cards successfully")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    db = SessionLocal()
    try:
        seed_cards(db)
    finally:
        db.close()
