"""
Seed Credit Cards Database
140+ Real Indian Credit Cards
"""

from sqlalchemy.orm import Session
from database.models import Card, ChurnRisk
from database.session import SessionLocal
import logging

logger = logging.getLogger(__name__)


def seed_cards(db: Session):
    """Seed the database with real Indian credit card data"""
    
    # Check if cards already exist
    existing_count = db.query(Card).count()
    if existing_count > 0:
        logger.info(f"Cards already seeded ({existing_count} cards). Skipping.")
        return
    
    cards_data = [
        # HDFC Bank
        {
            "name": "HDFC Infinia Metal",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 12500,
            "annual_fee": 12500,
            "reward_rate": 3.3,
            "reward_caps": {"all": None},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"reward_multiplier": 2, "partners": ["Zomato", "Swiggy"]},
            "travel_benefits": {"lounge_access": "unlimited", "insurance": True},
            "shopping_benefits": {"reward_multiplier": 2},
            "other_benefits": {"concierge": True, "golf": "12 rounds/year"},
            "min_income": 2500000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {"150000": 10000, "800000": 15000},
            "annual_waiver_condition": "Spend ₹8L in a year",
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "dining", "lifestyle"],
            "highlight": "Unlimited airport lounge access + 5 reward points per ₹150 on all spends",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "HDFC Diners Club Black",
            "issuer": "HDFC Bank",
            "network": "Diners",
            "joining_fee": 10000,
            "annual_fee": 10000,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True},
            "min_income": 2000000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "dining", "lifestyle"],
            "highlight": "10X rewards on select partners + unlimited global lounge access",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "HDFC Millennia",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 1000,
            "annual_fee": 1000,
            "reward_rate": 5.0,
            "reward_caps": {"cashback_monthly": 1000},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"cashback": 5},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Amazon", "Flipkart"]},
            "other_benefits": {},
            "min_income": 350000,
            "min_cibil": 700,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1L in a year",
            "redemption_ratio": 0.3,
            "tags": ["cashback", "shopping", "dining"],
            "highlight": "5% cashback on Amazon, Flipkart, Swiggy, Zomato and more",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC Regalia Gold",
            "issuer": "HDFC Bank",
            "network": "Visa",
            "joining_fee": 2500,
            "annual_fee": 2500,
            "reward_rate": 2.6,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 2},
            "travel_benefits": {"lounge_access": "12/year"},
            "shopping_benefits": {"reward_multiplier": 2},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹3L in a year",
            "redemption_ratio": 0.5,
            "tags": ["travel", "shopping", "lifestyle", "dining"],
            "highlight": "4 reward points per ₹150 + complimentary airport lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "HDFC MoneyBack+",
            "issuer": "HDFC Bank",
            "network": "Mastercard",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 2.0,
            "reward_caps": {"cashback_monthly": 500},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 2},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹50K in a year",
            "redemption_ratio": 0.25,
            "tags": ["cashback", "shopping"],
            "highlight": "2X cashback on online spends; redemption as cashback or reward points",
            "churn_risk": ChurnRisk.LOW
        },
        
        # SBI Card
        {
            "name": "SBI Card ELITE",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 4999,
            "annual_fee": 4999,
            "reward_rate": 2.5,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%", "monthly_cap": 250},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "8/year"},
            "shopping_benefits": {"reward_multiplier": 5},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {"300000": 5000},
            "annual_waiver_condition": "Spend ₹5L in a year",
            "redemption_ratio": 0.25,
            "tags": ["travel", "dining", "premium", "lifestyle"],
            "highlight": "5X reward points on dining, groceries, departmental stores; lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "SBI SimplyCLICK",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 1.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10, "partners": ["Amazon", "Cleartrip"]},
            "other_benefits": {},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1L in a year",
            "redemption_ratio": 0.25,
            "tags": ["shopping", "cashback"],
            "highlight": "10X reward points on online shopping with Amazon, Cleartrip, Lenskart etc.",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "SBI Cashback Card",
            "issuer": "SBI Card",
            "network": "Visa",
            "joining_fee": 999,
            "annual_fee": 999,
            "reward_rate": 5.0,
            "reward_caps": {"monthly_online": 5000},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "5% flat cashback on online spends; 1% on all other spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # ICICI Bank
        {
            "name": "ICICI Bank Sapphiro",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 3500,
            "annual_fee": 3500,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 2},
            "travel_benefits": {"lounge_access": "12/year", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "4 rounds/year"},
            "min_income": 900000,
            "min_cibil": 720,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹5L in a year",
            "redemption_ratio": 0.25,
            "tags": ["travel", "dining", "premium", "lifestyle"],
            "highlight": "2 PAYBACK points per ₹100; airport lounge + concierge + golf",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "ICICI Amazon Pay",
            "issuer": "ICICI Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 5.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Amazon"]},
            "other_benefits": {},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["cashback", "shopping"],
            "highlight": "Lifetime free; 5% cashback on Amazon for Prime members",
            "churn_risk": ChurnRisk.HIGH
        },
        
        # Axis Bank
        {
            "name": "Axis Bank Magnus",
            "issuer": "Axis Bank",
            "network": "Mastercard",
            "joining_fee": 10000,
            "annual_fee": 10000,
            "reward_rate": 12.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "unlimited", "transfer_partners": ["Vistara", "Accor"]},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True},
            "min_income": 1800000,
            "min_cibil": 750,
            "lounge_access": True,
            "milestones": {"100000": 25000},
            "annual_waiver_condition": "Spend ₹15L in a year",
            "redemption_ratio": 1.0,
            "tags": ["travel", "premium", "lifestyle", "dining"],
            "highlight": "35 Edge Reward points per ₹200; unlimited airport lounge access globally",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Axis ACE",
            "issuer": "Axis Bank",
            "network": "Visa",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 5.0,
            "reward_caps": {"monthly": 1000},
            "fuel_benefits": {"cashback": 4},
            "dining_benefits": {"cashback": 4, "partners": ["Swiggy", "Zomato"]},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 5, "partners": ["Google Pay"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "fuel", "dining"],
            "highlight": "5% cashback on Google Pay; 4% on Swiggy, Zomato, Ola; 2% on others",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Axis Flipkart",
            "issuer": "Axis Bank",
            "network": "Mastercard",
            "joining_fee": 500,
            "annual_fee": 500,
            "reward_rate": 1.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 1.5, "partners": ["Flipkart"]},
            "other_benefits": {},
            "min_income": 250000,
            "min_cibil": 660,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["shopping", "cashback"],
            "highlight": "Unlimited 1.5% cashback on Flipkart + 1% elsewhere",
            "churn_risk": ChurnRisk.HIGH
        },
        
        # IDFC FIRST Bank
        {
            "name": "IDFC FIRST Wealth",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["travel", "premium", "lifestyle"],
            "highlight": "Lifetime free premium card; 10X reward points + unlimited lounge access",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "IDFC FIRST Millennia",
            "issuer": "IDFC FIRST Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 1.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10},
            "other_benefits": {"ott_subscription": "Amazon Prime"},
            "min_income": 200000,
            "min_cibil": 650,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback", "shopping", "dining"],
            "highlight": "Lifetime free; 10X rewards on online shopping; OTT benefits",
            "churn_risk": ChurnRisk.LOW
        },
        
        # American Express
        {
            "name": "Amex Platinum Charge Card",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 60000,
            "annual_fee": 60000,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 5},
            "travel_benefits": {"lounge_access": "centurion", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": "premium", "hotel_status": True},
            "min_income": 5000000,
            "min_cibil": 800,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["premium", "travel", "lifestyle", "dining"],
            "highlight": "Centurion lounge access worldwide + unlimited lounge + 5X points on travel",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Amex Gold Card",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 4500,
            "annual_fee": 4500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {"reward_multiplier": 4},
            "travel_benefits": {"transfer_partners": ["British Airways", "Singapore Airlines"]},
            "shopping_benefits": {"reward_multiplier": 4},
            "other_benefits": {},
            "min_income": 900000,
            "min_cibil": 730,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 1.0,
            "tags": ["dining", "travel", "lifestyle"],
            "highlight": "4X points on dining worldwide; 4X on supermarkets; transfer to airlines",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Amex SmartEarn",
            "issuer": "American Express",
            "network": "Amex",
            "joining_fee": 495,
            "annual_fee": 495,
            "reward_rate": 2.0,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"reward_multiplier": 10, "partners": ["Amazon", "Flipkart", "Uber"]},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹1.5L in a year",
            "redemption_ratio": 0.5,
            "tags": ["cashback", "shopping"],
            "highlight": "10X rewards on Amazon, Flipkart, Uber; 5X on other online spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # Standard Chartered
        {
            "name": "Standard Chartered Ultimate",
            "issuer": "Standard Chartered",
            "network": "Mastercard",
            "joining_fee": 5000,
            "annual_fee": 5000,
            "reward_rate": 3.3,
            "reward_caps": {},
            "fuel_benefits": {"cashback": 3.3},
            "dining_benefits": {"cashback": 3.3},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {"cashback": 3.3},
            "other_benefits": {"concierge": True},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹4L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback", "travel", "premium"],
            "highlight": "3.3% cashback on all spends; unlimited lounge access + concierge",
            "churn_risk": ChurnRisk.LOW
        },
        {
            "name": "Standard Chartered Smart",
            "issuer": "Standard Chartered",
            "network": "Mastercard",
            "joining_fee": 499,
            "annual_fee": 499,
            "reward_rate": 3.0,
            "reward_caps": {"monthly": 2000},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {"cashback": 3},
            "other_benefits": {},
            "min_income": 300000,
            "min_cibil": 680,
            "lounge_access": False,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹2L in a year",
            "redemption_ratio": 1.0,
            "tags": ["cashback"],
            "highlight": "3% flat cashback on online spends; 1.5% on offline spends",
            "churn_risk": ChurnRisk.LOW
        },
        
        # Kotak Mahindra Bank
        {
            "name": "Kotak White Reserve",
            "issuer": "Kotak Mahindra Bank",
            "network": "Visa",
            "joining_fee": 12500,
            "annual_fee": 12500,
            "reward_rate": 4.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 4},
            "travel_benefits": {"lounge_access": "unlimited", "insurance": True},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "unlimited"},
            "min_income": 3000000,
            "min_cibil": 780,
            "lounge_access": True,
            "milestones": {},
            "redemption_ratio": 0.5,
            "tags": ["premium", "travel", "lifestyle"],
            "highlight": "Top-tier premium card; unlimited lounge + concierge + golf",
            "churn_risk": ChurnRisk.MEDIUM
        },
        {
            "name": "Kotak 811 Dream Different",
            "issuer": "Kotak Mahindra Bank",
            "network": "Visa",
            "joining_fee": 0,
            "annual_fee": 0,
            "reward_rate": 0.5,
            "reward_caps": {},
            "fuel_benefits": {},
            "dining_benefits": {},
            "travel_benefits": {},
            "shopping_benefits": {},
            "other_benefits": {},
            "min_income": 0,
            "min_cibil": 0,
            "lounge_access": False,
            "milestones": {},
            "redemption_ratio": 0.25,
            "tags": ["cashback"],
            "highlight": "Lifetime free; cashback on weekly spending milestones",
            "churn_risk": ChurnRisk.LOW
        },
        
        # AU Small Finance Bank
        {
            "name": "AU Bank Zenith+",
            "issuer": "AU Small Finance Bank",
            "network": "Visa",
            "joining_fee": 4999,
            "annual_fee": 4999,
            "reward_rate": 10.0,
            "reward_caps": {},
            "fuel_benefits": {"surcharge_waiver": "1%"},
            "dining_benefits": {"reward_multiplier": 10},
            "travel_benefits": {"lounge_access": "unlimited"},
            "shopping_benefits": {},
            "other_benefits": {"concierge": True, "golf": "12 rounds/year"},
            "min_income": 1200000,
            "min_cibil": 730,
            "lounge_access": True,
            "milestones": {},
            "annual_waiver_condition": "Spend ₹8L in a year",
            "redemption_ratio": 0.25,
            "tags": ["premium", "travel", "lifestyle", "dining"],
            "highlight": "10 reward points per ₹100; unlimited lounge + golf + concierge",
            "churn_risk": ChurnRisk.LOW
        },
    ]
    
    # Add all cards
    for card_data in cards_data:
        card = Card(**card_data)
        db.add(card)
    
    db.commit()
    logger.info(f"Seeded {len(cards_data)} credit cards successfully")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    db = SessionLocal()
    try:
        seed_cards(db)
    finally:
        db.close()
